services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: emb-payment-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp         # don't overwrite tmp build files
    working_dir: /app
    depends_on:
      - db
    environment:
      # Server Config
      - PORT=8080
      - GIN_MODE=debug
      # DB
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=emb_db
      # Redis
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
      # APPLICATION
      - APP_NAME=EMB Payment Service
      - APP_VERSION=1.0.0
    networks:
      - backend_network

  db:
    image: postgres:15
    container_name: emb_payment_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emb_db
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  # redis:
  #   image: redis:7-alpine
  #   container_name: emb_payment_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data
  #   command: redis-server --appendonly yes
  #   environment:
  #     - REDIS_PASSWORD=redis
  #   networks:
  #     - backend_network

volumes:
  pgdata:
  redisdata:

networks:
  backend_network:
    driver: bridge
