# Dockerfile.dev
# Using alpine for smaller image size
FROM golang:1.25-alpine

# Install required tools
RUN apk add --no-cache git

# Set env so Go binaries are on PATH
ENV PATH=$PATH:/go/bin

# Install Air for hot reload
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go.mod first for dependency caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose app port
EXPOSE 8080

# Run Air with config
CMD ["air", "-c", ".air.toml"]
